version: 2

defaults: &defaults
  shell: /bin/bash --login
  docker:
    - image: circleci/node:10.16.0-stretch

jobs:
        
  publish:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set NPMJS Registry
          command: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
      - run: npm install
      - run:
          name: Semantic Release
          # Must include on the npx command any packages for any plugins specified in .releaserc that are not part of the main semantic-release package
          # See: https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md
          command: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release

workflows:
  version: 2
  build_publish:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master